using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class BIBLE_DEF : MonoBehaviour
{
    readonly int BOOK_MAX = 66;
    readonly string[] BOOK_NAME = new string[]
    {
        "창세기",
        "출애굽기",
        "레위기",
        "민수기",
        "신명기",
        "여호수아",
        "요한계시록"
    };
    readonly int[] CHAPTER_MAX = new int[] {50,
                                                40,
                                                27,
                                                36,
                                                34,
                                                24,
                                                21,
                                                4,
                                                31,
                                                24,
                                                22,
                                                25,
                                                29,
                                                36,
                                                10,
                                                13,
                                                10,
                                                42,
                                                150,
                                                31,
                                                12,
                                                8,
                                                66,
                                                52,
                                                5,
                                                48,
                                                12,
                                                14,
                                                3,
                                                9,
                                                1,
                                                4,
                                                7,
                                                3,
                                                3,
                                                3,
                                                2,
                                                14,
                                                4,
                                                28,
                                                16,
                                                24,
                                                21,
                                                28,
                                                16,
                                                16,
                                                13,
                                                6,
                                                6,
                                                4,
                                                4,
                                                5,
                                                3,
                                                6,
                                                4,
                                                3,
                                                1,
                                                13,
                                                5,
                                                5,
                                                3,
                                                5,
                                                1,
                                                1,
                                                1,
                                                22};
}
